# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pilight
version: "v8.1.5"
slug: pilight
description: Pilight server add-on
url: "https://github.com/lgp1985/home-assistant.io-addon/tree/main/pilight"
arch:
- arm64
init: false
map:
- share:rw
options:
  gpio_platform: "str?"
  hardware:
    sender: 4
    receiver: 24
schema: false
image: "lgp1985/pilight-addon-{arch}"
gpio: true
privileged:
- SYS_RAWIO
